apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: tekton-alert
spec:
  providerRef:
    name: tekton-el-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: go-demo
      namespace: flux-system
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
