apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-on-release-demo-sa
subjects:
- kind: ServiceAccount
  name: demo-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-on-release-role
